version: '3.8'

services:
  travel-agent-dev:
    build: 
      context: .
      target: backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/src
      - ENVIRONMENT=development
    volumes:
      - ./src:/app/src
      - ./travel_agent.py:/app/travel_agent.py
      - ./api.py:/app/api.py
      - ./start.py:/app/start.py
      - ./data:/app/data
    restart: unless-stopped
    command: ["python", "api.py"]

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - travel-agent-dev

# No additional services needed - using free cloud LLM
