version: '3.8'
services:
  travel-agent:
    build: .
    ports:
      - "8000:8000"
    environment:
      - USE_LOCAL_LLM=true
      - OLLAMA_MODEL=llama3.1:8b
    volumes:
      - ./data:/app/data
    restart: unless-stopped

