/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        // Atlas Brand Colors
        'atlas-primary': {
          darkest: 'var(--brand-primary-darkest)',
          dark: 'var(--brand-primary-dark)',
          main: 'var(--brand-primary-main)',
          light: 'var(--brand-primary-light)',
          lighter: 'var(--brand-primary-lighter)',
        },
        'atlas-secondary': {
          dark: 'var(--brand-secondary-dark)',
          main: 'var(--brand-secondary-main)',
          light: 'var(--brand-secondary-light)',
          lighter: 'var(--brand-secondary-lighter)',
        },
        'atlas-ai': {
          dark: 'var(--brand-accent-ai-dark)',
          main: 'var(--brand-accent-ai-main)',
          light: 'var(--brand-accent-ai-light)',
          lighter: 'var(--brand-accent-ai-lighter)',
        },
        // Semantic Colors
        'atlas-success': {
          dark: 'var(--status-success-dark)',
          main: 'var(--status-success-main)',
          bg: 'var(--status-success-bg)',
        },
        'atlas-error': {
          dark: 'var(--status-error-dark)',
          main: 'var(--status-error-main)',
          bg: 'var(--status-error-bg)',
        },
        'atlas-warning': {
          dark: 'var(--status-warning-dark)',
          main: 'var(--status-warning-main)',
          bg: 'var(--status-warning-bg)',
        },
        'atlas-info': {
          dark: 'var(--status-info-dark)',
          main: 'var(--status-info-main)',
          bg: 'var(--status-info-bg)',
        },
        // UI Colors
        'atlas-bg': 'var(--ui-bg)',
        'atlas-card-bg': 'var(--ui-card-bg)',
        'atlas-text-primary': 'var(--text-primary)',
        'atlas-text-secondary': 'var(--text-secondary)',
        'atlas-text-tertiary': 'var(--text-tertiary)',
        'atlas-border': 'var(--border)',
        'atlas-border-subtle': 'var(--border-subtle)',
        // Data Visualization
        'atlas-dataviz': {
          1: 'var(--dataviz-1)',
          2: 'var(--dataviz-2)',
          3: 'var(--dataviz-3)',
          4: 'var(--dataviz-4)',
          5: 'var(--dataviz-5)',
          6: 'var(--dataviz-6)',
          7: 'var(--dataviz-7)',
          8: 'var(--dataviz-8)',
        },
        // Legacy shadcn/ui colors for compatibility
        border: 'var(--border)',
        input: 'var(--border)',
        ring: 'var(--focus-ring)',
        background: 'var(--ui-bg)',
        foreground: 'var(--text-primary)',
        primary: {
          DEFAULT: 'var(--brand-primary-main)',
          foreground: 'var(--global-white)',
        },
        secondary: {
          DEFAULT: 'var(--brand-secondary-main)',
          foreground: 'var(--global-white)',
        },
        destructive: {
          DEFAULT: 'var(--status-error-main)',
          foreground: 'var(--global-white)',
        },
        muted: {
          DEFAULT: 'var(--border-subtle)',
          foreground: 'var(--text-tertiary)',
        },
        accent: {
          DEFAULT: 'var(--brand-accent-ai-main)',
          foreground: 'var(--global-white)',
        },
        popover: {
          DEFAULT: 'var(--ui-card-bg)',
          foreground: 'var(--text-primary)',
        },
        card: {
          DEFAULT: 'var(--ui-card-bg)',
          foreground: 'var(--text-primary)',
        },
      },
      fontFamily: {
        sans: ['var(--font-family-sans)'],
        mono: ['var(--font-family-mono)'],
        display: ['var(--font-family-display)'],
        hebrew: ['var(--font-family-sans)', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        xs: ['var(--text-xs)', { lineHeight: 'var(--leading-tight)' }],
        sm: ['var(--text-sm)', { lineHeight: 'var(--leading-snug)' }],
        base: ['var(--text-base)', { lineHeight: 'var(--leading-normal)' }],
        lg: ['var(--text-lg)', { lineHeight: 'var(--leading-relaxed)' }],
        xl: ['var(--text-xl)', { lineHeight: 'var(--leading-relaxed)' }],
        '2xl': ['var(--text-2xl)', { lineHeight: 'var(--leading-snug)' }],
        '3xl': ['var(--text-3xl)', { lineHeight: 'var(--leading-tight)' }],
        '4xl': ['var(--text-4xl)', { lineHeight: 'var(--leading-tight)' }],
        '5xl': ['var(--text-5xl)', { lineHeight: 'var(--leading-tight)' }],
        '6xl': ['var(--text-6xl)', { lineHeight: 'var(--leading-tight)' }],
      },
      fontWeight: {
        light: 'var(--font-weight-light)',
        normal: 'var(--font-weight-normal)',
        medium: 'var(--font-weight-medium)',
        semibold: 'var(--font-weight-semibold)',
        bold: 'var(--font-weight-bold)',
        extrabold: 'var(--font-weight-extrabold)',
      },
      spacing: {
        0: 'var(--space-0)',
        1: 'var(--space-1)',
        2: 'var(--space-2)',
        3: 'var(--space-3)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        8: 'var(--space-8)',
        10: 'var(--space-10)',
        12: 'var(--space-12)',
        16: 'var(--space-16)',
        20: 'var(--space-20)',
        24: 'var(--space-24)',
        32: 'var(--space-32)',
        40: 'var(--space-40)',
        48: 'var(--space-48)',
        56: 'var(--space-56)',
        64: 'var(--space-64)',
      },
      borderRadius: {
        none: 'var(--radius-none)',
        sm: 'var(--radius-sm)',
        base: 'var(--radius-base)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        '3xl': 'var(--radius-3xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        base: 'var(--shadow-base)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        inner: 'var(--shadow-inner)',
      },
      transitionDuration: {
        75: 'var(--duration-75)',
        100: 'var(--duration-100)',
        150: 'var(--duration-150)',
        200: 'var(--duration-200)',
        300: 'var(--duration-300)',
        500: 'var(--duration-500)',
        700: 'var(--duration-700)',
        1000: 'var(--duration-1000)',
      },
      transitionTimingFunction: {
        linear: 'var(--ease-linear)',
        in: 'var(--ease-in)',
        out: 'var(--ease-out)',
        'in-out': 'var(--ease-in-out)',
      },
      screens: {
        sm: 'var(--breakpoint-sm)',
        md: 'var(--breakpoint-md)',
        lg: 'var(--breakpoint-lg)',
        xl: 'var(--breakpoint-xl)',
        '2xl': 'var(--breakpoint-2xl)',
      },
      zIndex: {
        dropdown: 'var(--z-index-dropdown)',
        sticky: 'var(--z-index-sticky)',
        fixed: 'var(--z-index-fixed)',
        'modal-backdrop': 'var(--z-index-modal-backdrop)',
        modal: 'var(--z-index-modal)',
        popover: 'var(--z-index-popover)',
        tooltip: 'var(--z-index-tooltip)',
        toast: 'var(--z-index-toast)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'fade-out': {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        'slide-in-from-top': {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(0)' },
        },
        'slide-in-from-bottom': {
          '0%': { transform: 'translateY(100%)' },
          '100%': { transform: 'translateY(0)' },
        },
        'slide-in-from-left': {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        'slide-in-from-right': {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        'scale-in': {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        'scale-out': {
          '0%': { transform: 'scale(1)', opacity: '1' },
          '100%': { transform: 'scale(0.95)', opacity: '0' },
        },
        'spin-slow': {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
        'pulse-ai': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
        'bounce-gentle': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down var(--duration-200) var(--ease-out)',
        'accordion-up': 'accordion-up var(--duration-200) var(--ease-out)',
        'fade-in': 'fade-in var(--duration-300) var(--ease-out)',
        'fade-out': 'fade-out var(--duration-200) var(--ease-in)',
        'slide-in-from-top': 'slide-in-from-top var(--duration-300) var(--ease-out)',
        'slide-in-from-bottom': 'slide-in-from-bottom var(--duration-300) var(--ease-out)',
        'slide-in-from-left': 'slide-in-from-left var(--duration-300) var(--ease-out)',
        'slide-in-from-right': 'slide-in-from-right var(--duration-300) var(--ease-out)',
        'scale-in': 'scale-in var(--duration-200) var(--ease-out)',
        'scale-out': 'scale-out var(--duration-150) var(--ease-in)',
        'spin-slow': 'spin-slow 3s var(--ease-linear) infinite',
        'pulse-ai': 'pulse-ai 2s var(--ease-in-out) infinite',
        'bounce-gentle': 'bounce-gentle 1s var(--ease-in-out) infinite',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};